### ISSUE TITLE
Question about previous frames.

### ISSUE THREAD

**Issue by BorisKourt** [GameTechDev/ChatHeads#1]
Hi,

I am running a very similar setup to your `RealsenseMgr` but I am having an issue that is a bit over my head. Everything appears to work, no memory leaks, data is cleared, and I've tested both `memcpy` and a more safe (slower) solution (`reserve` and `insert` into vector to use its `.data()` for drawing in other thread.)

Unfortunately every once in a while the frame that I get from the RSSDK is a similar to 3 - 10 frames back. So there is a visible flicker of a previous image in capture. 

This happens both in Segmented and Color data. 

I even saved the frames to disk, hoping it would be a rendering inconsistency. But no luck, I can see a near/duplicate of a prior frame saved to disk as well.

Have you had this problem? Do you know how I would go about debugging it?

Thanks for any advice,
Boris

**Comment by rajabala** [comment]
Haven't faced this issue before. Are you DCM and SDK versions upto date?

**Comment by BorisKourt** [comment]
I am currently running:

---

<p>SDK and components versions:<ul>
<li>      Intel(R) RealSense(TM) SDK
     10.0.26.396</li>
<li>      Intel(R) RealSense(TM) SDK Runtime
     6.0.21.6598</li>
<li>      Intel(R) RealSense(TM) Depth Camera Manager
     1.4.27.52404</li>
<li>      Intel(R) RealSense(TM) 3D Camera
     2780</li>
</ul></p>

<p>'No update is available'</p>

---

**Comment by rajabala** [comment]
I'd suggest posting this issue at the realsense forums since it concerns
the SDK.
https://software.intel.com/en-us/forums/realsense

**Comment by BorisKourt** [comment]
Will try, though haven't had a lot of luck with the dev forums in the past.

Closing this, thanks!
